# Generated by Django 5.1.7 on 2025-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_username_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='user_47f5bcb7-0caf-44f2-bfed-1ed41c0647b6', max_length=255, null=True),
        ),
    ]
