# Generated by Django 5.1.7 on 2025-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='typeLanKarakalpak',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='typeLanKrill',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='typeLanRu',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='typeLanUz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nameLanKarakalpak',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nameLanKrill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nameLanRu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='nameLanUz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='user_4b96b712-a54f-49eb-a0b1-084c5bd7f2b3', max_length=255, null=True),
        ),
    ]
