# Generated by Django 5.1.7 on 2025-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='typeLanUz',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='nameLanUz',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='user_f6283fae-a887-4da6-a509-02075c2a62a9', max_length=255, null=True),
        ),
    ]
